version: "3.9"
services:

  java_app:
    container_name: java_app
    image: crud-java:1.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:mariadb://java_db:3306/mydatabase
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: mariadb:latest
    ports:
      - 3305:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: usuario
      MYSQL_PASSWORD: password